"""Add profile and settings fields to Student model

Revision ID: 24f9ccdcf645
Revises: 
Create Date: 2025-09-12 03:38:50.786437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f9ccdcf645'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('college', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sms_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('profile_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_online_status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('timezone')
        batch_op.drop_column('language')
        batch_op.drop_column('show_online_status')
        batch_op.drop_column('profile_public')
        batch_op.drop_column('push_notifications')
        batch_op.drop_column('sms_notifications')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('college')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
