"""Add dark mode preference field

Revision ID: 460636822a2c
Revises: 24f9ccdcf645
Create Date: 2025-09-12 03:47:09.944836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460636822a2c'
down_revision = '24f9ccdcf645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dark_mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('dark_mode')

    # ### end Alembic commands ###
